### ISSUE TITLE
Define Scope

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-ematkinsongit-1#1]
# Description
Define scope for version 1.0 of the project.

## Requirements
- [ ] Define milestones for each sprint.
- [ ] Define final deliverable for v1.
- [ ] DM your advisor for approval.
- [ ] [Update your solo project repository `About` in GitHub](https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github).

**Comment by ematkinsongit** [comment]
resolved #1 Define Scope
